apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortio
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
      - name: fortio
        image: fortio/fortio
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fortio-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: fortio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fortio-ingress
spec:
  ingressClassName: gce
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: fortio-service
            port:
              number: 80

