apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  namespace: test
spec:
  nodeName: ${NODENAME}
  containers:
  - image: ${IMAGE_REGISTRY}/alpine:3.18.4
    name: alpine-3.18
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 50Mi
  preemptionPolicy: PreemptLowerPriority
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
