apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  namespace: ${TEST_NAMESPACE_1}
spec:
  nodeName: ${NODENAME}
  containers:
    - image: ${IMAGE_REGISTRY}/alpine-curl:8.3.0
      imagePullPolicy: Always
      name: alpine-curl
      command:
        - /bin/sh
        - -c
        - sleep 1d
      resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 50Mi
  imagePullSecrets:
    - name: ecr-login
  preemptionPolicy: PreemptLowerPriority
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
