---
apiVersion: v1
kind: Namespace
metadata:
  name: httpd
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample
  name: httpd-a
  namespace: httpd
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: httpd-a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample
        k8s-app: httpd-a
        component: server
        team: sreaster
        phase: blue
    spec:
      containers:
      - image: httpd
        imagePullPolicy: Always
        name: httpd
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample
  name: httpd-a
  namespace: httpd
spec:
  clusterIP: 100.67.170.97
  clusterIPs:
  - 100.67.170.97
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
  selector:
    k8s-app: httpd-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample
  name: httpd-b
  namespace: httpd
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: httpd-b
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample
        k8s-app: httpd-b
        component: server
        team: sreaster
        phase: green
    spec:
      containers:
      - image: httpd
        imagePullPolicy: Always
        name: httpd
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            memory: 200Mi
