version: '3'

tasks:
  start-lima:
    desc: start lima instance
    cmds:
      - limactl start --name ebpf-dev {{.TASKFILE_DIR}}/lima-ebpf.yaml --tty=false

  build:
    desc: "Build the Docker image for eBPF"
    cmds:
      - echo "Building Docker image..."
      - docker build -t ebpf-cloud-run:latest .

  push:
    desc: "Push the image to Google Container Registry (GCR)"
    vars:
      registry: "gcr.io"
      project_id: "{{.PROJECT_ID}}"
    cmds:
      - echo "Tagging the image for GCR..."
      - docker tag ebpf-cloud-run {{.registry}}/{{.project_id}}/ebpf-cloud-run
      - echo "Pushing the image to GCR..."
      - docker push {{.registry}}/{{.project_id}}/ebpf-cloud-run
    env:
      PROJECT_ID:
        sh: echo "$PROJECT_ID"

  deploy:
    desc: "Deploy the eBPF Docker image to Cloud Run"
    cmds:
      - echo "Deploying the image to Cloud Run..."
      - gcloud run deploy ebpf-demo \
          --image gcr.io/{{.PROJECT_ID}}/ebpf-cloud-run \
          --platform managed \
          --region {{.REGION}} \
          --allow-unauthenticated
    env:
      PROJECT_ID:
        sh: echo "$PROJECT_ID"

  all:
    desc: "Run all tasks: build, test locally, push, and deploy"
    cmds:
      - task: build
      - task: push
      - task: deploy

  help:
    desc: Show list of available tasks and their descriptions
    cmds:
      - task --list
