---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ebpf
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-ds
  namespace: test-ebpf
spec:
  selector:
    matchLabels:
      app: ebpf-ds
  template:
    metadata:
      labels:
        app: ebpf-ds
    spec:
      hostPID: true  # Required to access host syscalls
      nodeSelector:
        workload: noisy-node
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "noisy-node"
        effect: "NoSchedule"

      containers:
      - name: ebpf-ds
        image: ${IMAGE}
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        securityContext:
          privileged: true  # Required for eBPF operations
        volumeMounts:
        - name: sys-kernel-debug
          mountPath: /sys/kernel/debug
        - name: sys-fs-cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
      volumes:
      - name: sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug
      - name: sys-fs-cgroup
        hostPath:
          path: /sys/fs/cgroup
