---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ebpf
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-ebpf
  namespace: test-ebpf
spec:
  selector:
    matchLabels:
      app: my-ebpf
  template:
    metadata:
      labels:
        app: my-ebpf
    spec:
      hostPID: true  # Required to access host syscalls
      containers:
      - name: my-ebpf
        image: ${IMAGE_PATH}:${GIT_COMMIT}
        securityContext:
          privileged: true  # Required for eBPF operations
        volumeMounts:
        - name: sys-kernel-debug
          mountPath: /sys/kernel/debug
      volumes:
      - name: sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug
