---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-admin-sa
  namespace: platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-limited-sa
  namespace: platform
