apiVersion: v1
kind: Pod
metadata:
  name: test-without-proxy
spec:
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["/bin/sh"]
    args: ["-c","curl -f -v https://en.wikipedia.org/wiki/Kubernetes -o /dev/null", "curl -v http://httpbin.org/ip", "curl -v https://api.ipify.org", sleep infinity]

